# Generated by Django 6.0.5 on 2026-05-25 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='componentepc',
            name='form_factor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='componentepc',
            name='watts_recomendados',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='componentepc',
            name='tipo',
            field=models.CharField(choices=[('CPU', 'Procesador'), ('PLACA', 'Placa Madre'), ('RAM', 'Memoria RAM'), ('ALMACENAMIENTO', 'Almacenamiento'), ('GPU', 'Tarjeta de Video'), ('FUENTE', 'Fuente de Poder'), ('CASE', 'Gabinete'), ('MONITOR', 'Monitor'), ('TECLADO', 'Teclado'), ('MOUSE', 'Mouse'), ('AURICULARES', 'Auriculares'), ('MOUSEPAD', 'Mousepad'), ('UPS', 'Estabilizador UPS'), ('MICROFONO', 'Micrófono'), ('CAMARA', 'Cámara Web')], max_length=20),
        ),
    ]
